# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(size=(7,7))
t1

tensor([[0.9747, 0.4788, 0.1036, 0.4637, 0.7240, 0.5970, 0.3436],
        [0.0907, 0.6818, 0.0914, 0.4437, 0.7514, 0.7852, 0.3457],
        [0.2614, 0.2651, 0.7303, 0.0439, 0.0833, 0.8874, 0.1095],
        [0.0181, 0.2236, 0.6768, 0.6032, 0.9274, 0.9060, 0.8022],
        [0.2946, 0.9993, 0.9001, 0.4079, 0.7642, 0.4804, 0.8976],
        [0.0445, 0.9615, 0.8808, 0.6089, 0.5368, 0.8681, 0.9902],
        [0.4462, 0.3014, 0.9240, 0.1139, 0.6421, 0.6730, 0.1207]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
t2 = torch.rand(size=(1,7))
# Perform matrix multiplication 
result = torch.mm(t1, t2.T)
result

tensor([[1.6228],
        [1.4541],
        [0.8848],
        [2.4288],
        [2.4800],
        [2.6145],
        [1.4103]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(1,7)
# Matrix multiply tensors
result = torch.mm(t1,t2.T)
result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
RANDOM_ON_MPS = 1234
torch.mps.manual_seed(RANDOM_ON_MPS)
t1 = torch.rand(3,4)
torch.mps.manual_seed(RANDOM_ON_MPS)
t2 = torch.rand(3,4)
result = torch.mm(t1, t2.T)
result

tensor([[1.2808, 1.6567, 0.4594],
        [0.3999, 0.7339, 0.1714],
        [1.4180, 1.3416, 0.4959]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
print(torch.mps.is_available())
# Create two random tensors on GPU
t1 = torch.rand(size=(2,3), device='mps')
t2 = torch.rand(size=(2,3), device='mps')
t1, t2

True


(tensor([[0.4794, 0.7608, 0.8283],
         [0.8029, 0.6423, 0.0597]], device='mps:0'),
 tensor([[0.0223, 0.9878, 0.2711],
         [0.9123, 0.7672, 0.8879]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(t1, t2.T)
output

tensor([[0.9868, 1.7565],
        [0.6685, 1.2782]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
print(output.min())
# Find min
print(output.max())


tensor(0.6685, device='mps:0')
tensor(1.7565, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(output.argmax())
# Find arg min
print(output.argmin())

tensor(1, device='mps:0')
tensor(2, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t1 = torch.rand(size=(1,1,1,10))
print(t1)
# Remove single dimensions
print(t1.squeeze())

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
