# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(size=(7,7))
t1

tensor([[0.0193, 0.2610, 0.9184, 0.2996, 0.5902, 0.7683, 0.9460],
        [0.8148, 0.2196, 0.2290, 0.2688, 0.5459, 0.9752, 0.2326],
        [0.0706, 0.0621, 0.9342, 0.8019, 0.8857, 0.2479, 0.4118],
        [0.8072, 0.1084, 0.0054, 0.9897, 0.4029, 0.5259, 0.2436],
        [0.0182, 0.0089, 0.1255, 0.4963, 0.3717, 0.7242, 0.4377],
        [0.8656, 0.8693, 0.4017, 0.3632, 0.1371, 0.8627, 0.5796],
        [0.9291, 0.8182, 0.5283, 0.8117, 0.4664, 0.6072, 0.0026]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
t2 = torch.rand(size=(1,7))
# Perform matrix multiplication 
result = torch.mm(t1, t2.T)
result

tensor([[1.7061],
        [1.6987],
        [1.4626],
        [1.5988],
        [0.8447],
        [2.5081],
        [2.5600]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(1,7)
# Matrix multiply tensors
result = torch.mm(t1,t2.T)
result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
RANDOM_ON_MPS = 1234
torch.mps.manual_seed(RANDOM_ON_MPS)
t1 = torch.rand(3,4)
torch.mps.manual_seed(RANDOM_ON_MPS)
t2 = torch.rand(3,4)
result = torch.mm(t1, t2.T)
result

tensor([[0.2435, 1.0417, 1.3311],
        [0.8448, 1.1240, 1.3087],
        [0.6334, 1.3319, 1.7343]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
