In [3]:
import torch

In [5]:
data = [[1,2,3],
        [4,5,6]]
my_tensor = torch.tensor(data)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
my_tensor.shape

torch.Size([2, 3])

In [7]:
my_tensor.dtype

torch.int64

In [10]:
a = my_tensor
b = torch.tensor([[2,2,5],
                  [3,3,2]])

In [11]:
a+b

tensor([[3, 4, 8],
        [7, 8, 8]])

In [13]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

corrected_temperatures = adjustment + 2
print("Corrected temperatures:", corrected_temperatures)

Corrected temperatures: tensor([[4, 4, 4],
        [4, 4, 4]])


In [14]:
import torch.nn as nn

In [15]:
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]]
)
linear_layer = nn.Linear(in_features=3,out_features=2)

In [16]:
output = linear_layer(input_tensor)
output

tensor([[-0.2886, -0.2004]], grad_fn=<AddmmBackward0>)

![description](scher.png)

In [17]:
linear_layer.weight

Parameter containing:
tensor([[ 0.4007,  0.0567, -0.0006],
        [ 0.1393,  0.0049, -0.3107]], requires_grad=True)

In [18]:
linear_layer.bias

Parameter containing:
tensor([-0.4537, -0.3242], requires_grad=True)

![description](scher2.png)

In [ ]:
model = nn.Sequential(
    nn.Linear(n_features, 8), # n_features represents number of input features
    nn.Linear(8,4),
    nn.Linear(4, n_classes) # n_classes represents number of output classes
)

In [ ]:
model = nn.Sequential(
    nn.Linear(5, 8),
    nn.Linear(8,4),
    nn.Linear(4, 10)
)

In [19]:
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2)
)
total = 0
for parameter in model.parameters():
    total += parameter.numel()
total

46

![description](scher3.png)

In [20]:
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
output

tensor([[0.9975]])

In [21]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/Users/mclight/Downloads/GitHub/AI_Self-Study/.conda/lib/python3.11/site-packages/torch/nn/modules/module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
