## Neural Networks
![description](screen.png)

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.9.1


In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# Get tensor back as Python int
scaler.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR1 = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]],[[4,2,3],
                                   [3,6,9],
                                   [2,4,5]],[[2 ,2,3],
                                             [3,6,9],
                                             [2,4,5]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[4, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([3, 3, 3])

---------
### Random tensors

In [26]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5452, 0.1056, 0.2715, 0.9201],
        [0.6066, 0.2898, 0.5148, 0.4043],
        [0.4184, 0.4127, 0.0787, 0.4191]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

# Image tensor

In [ ]:
r_image_tensor = torch.rand(size=(3, 224, 224)) # colour, height, width
r_image_tensor.ndim, r_image_tensor.shape

(3, torch.Size([224, 224, 3]))

--------
## Masking

In [30]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

---------
## Creating a range of tensors and tensors-like

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
# Tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

------------
### Tensor datatypes
Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

In [62]:
float_32_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=None, 
                                                device='cpu',
                                                requires_grad=False)
float_32_tensor

tensor([3., 4., 9.])

In [63]:
float_32_tensor.dtype

torch.float32

In [64]:
float_64_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float64, 
                                                device='cpu',
                                                requires_grad=False)
float_64_tensor

tensor([3., 4., 9.], dtype=torch.float64)

In [65]:
float_64_tensor.dtype

torch.float64

In [66]:
float_32_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [71]:
float_16_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float16, 
                                                device='cpu',
                                                requires_grad=False)
float_16_tensor

tensor([3., 4., 9.], dtype=torch.float16)

In [72]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 81.])

In [73]:
float_16_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [74]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int,)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [75]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

-----------
### Getting information from tensors

dtype, shape, device

In [76]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5491, 0.6128, 0.5232, 0.0044],
        [0.5982, 0.9367, 0.5019, 0.5016],
        [0.1974, 0.0396, 0.9490, 0.5362]])

In [77]:
some_tensor.shape

torch.Size([3, 4])

In [78]:
some_tensor.size()

torch.Size([3, 4])

In [79]:
some_tensor.dtype

torch.float32

In [80]:
some_tensor.device

device(type='cpu')

-----------
### Manipulation tensors

1. The inner dimensions must match
2. The shape of matrix multiplication is the **outer dimension**

In [82]:
# Addition

t1 = torch.tensor([1,2,3])
t1 + 100

tensor([101, 102, 103])

In [83]:
# Multiplication
t1 * 12

tensor([12, 24, 36])

In [84]:
t1 - 10

tensor([-9, -8, -7])

In [87]:
t1 / 3

tensor([0.3333, 0.6667, 1.0000])

In [88]:
print(torch.add(t1, 3))

tensor([4, 5, 6])


In [89]:
print(torch.mul(t1, 3))

tensor([3, 6, 9])


In [93]:
# Matrix multiplication (Elementwise)
t1 * t1

tensor([1, 4, 9])

In [96]:
%%time
# Matrix multiplication
torch.matmul(t1, t1)

CPU times: user 111 μs, sys: 44 μs, total: 155 μs
Wall time: 148 μs


tensor(14)

In [97]:
%%time
value = 0
for i in range(len(t1)):
    value == t1[i] ** t1[i]
print(value)

0
CPU times: user 542 μs, sys: 1.23 ms, total: 1.77 ms
Wall time: 2.73 ms


One of the most common errors in deep learning: shape errors

In [100]:
# Shapes for matrix multiplications
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])
torch.mm(t1,t2) # torch.mm = torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [106]:
# Transpose
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8],[9,10],[11,12]])

print(t1.T)
print('\n', torch.mm(t1.T, t2), '\n')
print(torch.mm(t1, t2.T))

tensor([[1, 3, 5],
        [2, 4, 6]])

 tensor([[ 89,  98],
        [116, 128]]) 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [107]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [108]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [111]:
x.max(), x.min()

(tensor(90), tensor(0))

In [110]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [113]:
x.type(torch.float32).mean()

tensor(45.)

Finding positional min and max

In [114]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [115]:
x.argmin()

tensor(0)

In [116]:
x.argmax()

tensor(9)

----------
## Reshaping, stacking, squeezing and unsqueezing tensors

In [117]:
x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [120]:
x.reshape(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x.reshape(10,1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [ ]:
# Change the view
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
x.reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [ ]:
x.view(5,2)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])