## Neural Networks
![description](screen.png)

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.9.1


In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get tensor back as Python int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR1 = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]],[[4,2,3],
                                   [3,6,9],
                                   [2,4,5]],[[2 ,2,3],
                                             [3,6,9],
                                             [2,4,5]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[4, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR1.ndim

3

In [18]:
TENSOR1.shape

torch.Size([3, 3, 3])

---------
### Random tensors

In [19]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6729, 0.1809, 0.2454, 0.5713],
        [0.4623, 0.0251, 0.8295, 0.0459],
        [0.5893, 0.3695, 0.0612, 0.8866]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([3, 4])

# Image tensor

In [22]:
r_image_tensor = torch.rand(size=(3, 224, 224)) # colour, height, width
r_image_tensor.ndim, r_image_tensor.shape

(3, torch.Size([3, 224, 224]))

--------
## Masking

In [23]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

---------
## Creating a range of tensors and tensors-like

In [27]:
# use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
# Tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

------------
### Tensor datatypes
Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

In [30]:
float_32_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=None, 
                                                device='cpu',
                                                requires_grad=False)
float_32_tensor

tensor([3., 4., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_64_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float64, 
                                                device='cpu',
                                                requires_grad=False)
float_64_tensor

tensor([3., 4., 9.], dtype=torch.float64)

In [33]:
float_64_tensor.dtype

torch.float64

In [34]:
float_32_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [35]:
float_16_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float16, 
                                                device='cpu',
                                                requires_grad=False)
float_16_tensor

tensor([3., 4., 9.], dtype=torch.float16)

In [36]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 81.])

In [37]:
float_16_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [38]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int,)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

-----------
### Getting information from tensors

dtype, shape, device

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8020, 0.2666, 0.8189, 0.2196],
        [0.2254, 0.3316, 0.1558, 0.6412],
        [0.9345, 0.7575, 0.8465, 0.5212]])

In [41]:
some_tensor.shape

torch.Size([3, 4])

In [42]:
some_tensor.size()

torch.Size([3, 4])

In [43]:
some_tensor.dtype

torch.float32

In [44]:
some_tensor.device

device(type='cpu')

-----------
### Manipulation tensors

1. The inner dimensions must match
2. The shape of matrix multiplication is the **outer dimension**

In [45]:
# Addition

t1 = torch.tensor([1,2,3])
t1 + 100

tensor([101, 102, 103])

In [46]:
# Multiplication
t1 * 12

tensor([12, 24, 36])

In [47]:
t1 - 10

tensor([-9, -8, -7])

In [48]:
t1 / 3

tensor([0.3333, 0.6667, 1.0000])

In [49]:
print(torch.add(t1, 3))

tensor([4, 5, 6])


In [50]:
print(torch.mul(t1, 3))

tensor([3, 6, 9])


In [51]:
# Matrix multiplication (Elementwise)
t1 * t1

tensor([1, 4, 9])

In [52]:
%%time
# Matrix multiplication
torch.matmul(t1, t1)

CPU times: user 340 μs, sys: 816 μs, total: 1.16 ms
Wall time: 1.08 ms


tensor(14)

In [53]:
%%time
value = 0
for i in range(len(t1)):
    value == t1[i] ** t1[i]
print(value)

0
CPU times: user 406 μs, sys: 816 μs, total: 1.22 ms
Wall time: 773 μs


One of the most common errors in deep learning: shape errors

In [54]:
# Shapes for matrix multiplications
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])
torch.mm(t1,t2) # torch.mm = torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
# Transpose
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8],[9,10],[11,12]])

print(t1.T)
print('\n', torch.mm(t1.T, t2), '\n')
print(torch.mm(t1, t2.T))

tensor([[1, 3, 5],
        [2, 4, 6]])

 tensor([[ 89,  98],
        [116, 128]]) 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [56]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [58]:
x.max(), x.min()

(tensor(90), tensor(0))

In [59]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [60]:
x.type(torch.float32).mean()

tensor(45.)

Finding positional min and max

In [61]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
x.argmin()

tensor(0)

In [63]:
x.argmax()

tensor(9)

----------
## Reshaping, stacking, squeezing and unsqueezing tensors

In [64]:
x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [ ]:
x.reshape(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x.reshape(10,1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [ ]:
# Change the view
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [65]:
x.reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [66]:
x.view(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [67]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [68]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [69]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [70]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [71]:
# Squeeze and unsqueeze
x.shape

torch.Size([10])

In [72]:
x_reshaped = torch.tensor([[5,2,3,4,5,6,7,8,9]])
x_reshaped.shape

torch.Size([1, 9])

In [73]:
x_reshaped.squeeze().shape

torch.Size([9])

In [74]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [75]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [76]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [77]:
# Rearrenging the dimension of a target tensor
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [78]:
x_original[0,:,0] = 532
print(x_original[:,:,0])
x_permuted2 = x_original.permute(2,0,1)
x_permuted2

tensor([[5.3200e+02, 5.3200e+02, 5.3200e+02,  ..., 5.3200e+02, 5.3200e+02,
         5.3200e+02],
        [7.7237e-01, 5.0186e-01, 3.1671e-01,  ..., 6.8463e-01, 6.8043e-01,
         9.0259e-01],
        [3.4189e-01, 8.9786e-01, 4.0342e-01,  ..., 5.9837e-01, 7.1164e-01,
         8.5033e-01],
        ...,
        [1.8135e-02, 1.8843e-01, 5.4266e-01,  ..., 2.1018e-01, 7.4891e-01,
         1.8862e-01],
        [9.8485e-01, 1.8928e-01, 1.3965e-01,  ..., 9.8302e-01, 3.0846e-01,
         7.2698e-01],
        [4.0993e-01, 8.4169e-01, 7.6436e-01,  ..., 8.9836e-01, 5.9277e-01,
         4.4204e-02]])


tensor([[[5.3200e+02, 5.3200e+02, 5.3200e+02,  ..., 5.3200e+02,
          5.3200e+02, 5.3200e+02],
         [7.7237e-01, 5.0186e-01, 3.1671e-01,  ..., 6.8463e-01,
          6.8043e-01, 9.0259e-01],
         [3.4189e-01, 8.9786e-01, 4.0342e-01,  ..., 5.9837e-01,
          7.1164e-01, 8.5033e-01],
         ...,
         [1.8135e-02, 1.8843e-01, 5.4266e-01,  ..., 2.1018e-01,
          7.4891e-01, 1.8862e-01],
         [9.8485e-01, 1.8928e-01, 1.3965e-01,  ..., 9.8302e-01,
          3.0846e-01, 7.2698e-01],
         [4.0993e-01, 8.4169e-01, 7.6436e-01,  ..., 8.9836e-01,
          5.9277e-01, 4.4204e-02]],

        [[1.3366e-03, 5.0663e-02, 2.5498e-01,  ..., 4.1484e-02,
          4.9882e-01, 9.5420e-01],
         [3.7264e-01, 3.3397e-01, 8.6368e-02,  ..., 1.9491e-01,
          5.4488e-01, 9.4503e-01],
         [3.5824e-01, 9.6638e-02, 3.2976e-01,  ..., 1.6524e-01,
          6.4060e-01, 4.2788e-01],
         ...,
         [5.5773e-01, 2.8406e-01, 5.6134e-01,  ..., 8.9340e-01,
          5.556

----------
## Indexing (selecting data from tensors)
Similar with numpy

In [79]:
a = torch.arange(1,10).reshape(1,3,3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
a[0][0]

tensor([1, 2, 3])

In [82]:
# Last dimension
a[0][0][0]

tensor(1)

In [83]:
a[:,0]

tensor([[1, 2, 3]])

In [84]:
# Get all the values of 0th and 1stdimensions but ony ndex 1 of 2nd dimension
a[:,:,1]

tensor([[2, 5, 8]])

In [85]:
a[:,1,1]

tensor([5])

In [86]:
a[0,0,:]

tensor([1, 2, 3])

In [87]:
# Index on a to return 9
print(a[0, 2, 2])
print(a[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


---------
## PyTorch tensors & Numpy

In [88]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: it is float64, to change use this: 'type(torch.float32)'
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
# Change the value of array, what will this do to 'tensor'?
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [91]:
# Changing the tensor
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

---------
## Reproducbility (trying to take random out of random)

In [92]:
torch.rand(3,3)

tensor([[0.7310, 0.5076, 0.9676],
        [0.2883, 0.1233, 0.6676],
        [0.3576, 0.1334, 0.5844]])

In [93]:
r1 = torch.rand(3,4)
r2 = torch.rand(3,4)
r1, r2

(tensor([[0.6052, 0.6347, 0.6021, 0.7163],
         [0.5541, 0.6520, 0.0402, 0.9312],
         [0.4317, 0.8258, 0.0496, 0.5362]]),
 tensor([[0.2061, 0.8803, 0.3114, 0.2582],
         [0.2847, 0.6028, 0.6771, 0.3834],
         [0.8122, 0.0665, 0.8809, 0.0993]]))

In [94]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(3,4)

print(t1 == t2)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


------------
### Check for GPU access with PyTorch

In [95]:
torch.mps.is_available()

True

In [96]:
device = 'mps' if torch.mps.is_available() else 'cpu'
device

'mps'

In [97]:
torch.mps.device_count()

1

--------
## Putting tensors (and models) on the MPS
For faster computation

In [98]:
a1 = torch.tensor([1,2,3])

# Tensor not on MPS
print(tensor, tensor.device)

tensor([2., 2., 2., 2., 2., 2., 2.]) cpu


In [99]:
# Move tensor to MPS if available
m1 = a1.to(device)
device

'mps'

----------
### Moving tensors back to the CPU

In [101]:
m1.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [102]:
m1.cpu().numpy()

array([1, 2, 3])

---------
### Exercises