## Neural Networks
![description](screen.png)

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.9.1


In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [21]:
TENSOR1 = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]],[[1,2,3],
                                   [3,6,9],
                                   [2,4,5]],[[1,2,3],
                                             [3,6,9],
                                             [2,4,5]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [24]:
TENSOR1.ndim

3

In [25]:
TENSOR1.shape

torch.Size([3, 3, 3])

In [ ]:
s