## Neural Networks
![description](screen.png)

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(torch.__version__)

2.9.1


In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# Get tensor back as Python int
scaler.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR1 = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]],[[4,2,3],
                                   [3,6,9],
                                   [2,4,5]],[[2 ,2,3],
                                             [3,6,9],
                                             [2,4,5]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[4, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([3, 3, 3])

---------
### Random tensors

In [20]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4466, 0.9103, 0.3550, 0.1919],
        [0.3246, 0.2129, 0.6040, 0.5526],
        [0.1272, 0.8681, 0.5705, 0.4217]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

# Image tensor

In [23]:
r_image_tensor = torch.rand(size=(3, 224, 224)) # colour, height, width
r_image_tensor.ndim, r_image_tensor.shape

(3, torch.Size([3, 224, 224]))

--------
## Masking

In [24]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

---------
## Creating a range of tensors and tensors-like

In [28]:
# use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
# Tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

------------
### Tensor datatypes
Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

In [31]:
float_32_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=None, 
                                                device='cpu',
                                                requires_grad=False)
float_32_tensor

tensor([3., 4., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_64_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float64, 
                                                device='cpu',
                                                requires_grad=False)
float_64_tensor

tensor([3., 4., 9.], dtype=torch.float64)

In [34]:
float_64_tensor.dtype

torch.float64

In [35]:
float_32_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [36]:
float_16_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float16, 
                                                device='cpu',
                                                requires_grad=False)
float_16_tensor

tensor([3., 4., 9.], dtype=torch.float16)

In [37]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 81.])

In [38]:
float_16_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

In [39]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int,)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

-----------
### Getting information from tensors

dtype, shape, device

In [41]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0894, 0.7593, 0.9966, 0.5862],
        [0.4667, 0.6112, 0.2651, 0.7180],
        [0.0399, 0.4432, 0.0716, 0.2064]])

In [42]:
some_tensor.shape

torch.Size([3, 4])

In [43]:
some_tensor.size()

torch.Size([3, 4])

In [44]:
some_tensor.dtype

torch.float32

In [45]:
some_tensor.device

device(type='cpu')

-----------
### Manipulation tensors

1. The inner dimensions must match
2. The shape of matrix multiplication is the **outer dimension**

In [46]:
# Addition

t1 = torch.tensor([1,2,3])
t1 + 100

tensor([101, 102, 103])

In [47]:
# Multiplication
t1 * 12

tensor([12, 24, 36])

In [48]:
t1 - 10

tensor([-9, -8, -7])

In [49]:
t1 / 3

tensor([0.3333, 0.6667, 1.0000])

In [50]:
print(torch.add(t1, 3))

tensor([4, 5, 6])


In [51]:
print(torch.mul(t1, 3))

tensor([3, 6, 9])


In [52]:
# Matrix multiplication (Elementwise)
t1 * t1

tensor([1, 4, 9])

In [53]:
%%time
# Matrix multiplication
torch.matmul(t1, t1)

CPU times: user 690 μs, sys: 1.63 ms, total: 2.32 ms
Wall time: 2.54 ms


tensor(14)

In [54]:
%%time
value = 0
for i in range(len(t1)):
    value == t1[i] ** t1[i]
print(value)

0
CPU times: user 755 μs, sys: 1.57 ms, total: 2.33 ms
Wall time: 2.06 ms


One of the most common errors in deep learning: shape errors

In [55]:
# Shapes for matrix multiplications
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])
torch.mm(t1,t2) # torch.mm = torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [56]:
# Transpose
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t2 = torch.tensor([[7,8],[9,10],[11,12]])

print(t1.T)
print('\n', torch.mm(t1.T, t2), '\n')
print(torch.mm(t1, t2.T))

tensor([[1, 3, 5],
        [2, 4, 6]])

 tensor([[ 89,  98],
        [116, 128]]) 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [57]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [59]:
x.max(), x.min()

(tensor(90), tensor(0))

In [60]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [61]:
x.type(torch.float32).mean()

tensor(45.)

Finding positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
x.argmin()

tensor(0)

In [64]:
x.argmax()

tensor(9)

----------
## Reshaping, stacking, squeezing and unsqueezing tensors

In [65]:
x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [66]:
x.reshape(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [67]:
x.reshape(10,1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [68]:
# Change the view
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [69]:
x.reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [70]:
x.view(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [72]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [73]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [76]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [77]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [78]:
# Squeeze and unsqueeze
x.shape

torch.Size([10])

In [80]:
x_reshaped = torch.tensor([[5,2,3,4,5,6,7,8,9]])
x_reshaped.shape

torch.Size([1, 9])

In [85]:
x_reshaped.squeeze().shape

torch.Size([9])

In [88]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [91]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [92]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [95]:
# Rearrenging the dimension of a target tensor
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [104]:
x_original[0,:,0] = 532
print(x_original[:,:,0])
x_permuted2 = x_original.permute(2,0,1)
x_permuted2

tensor([[5.3200e+02, 5.3200e+02, 5.3200e+02,  ..., 5.3200e+02, 5.3200e+02,
         5.3200e+02],
        [9.9275e-01, 2.1228e-01, 3.9331e-01,  ..., 5.6738e-01, 6.7587e-01,
         1.0177e-01],
        [6.1023e-01, 6.9942e-01, 5.8117e-01,  ..., 8.5050e-01, 9.1666e-01,
         2.3597e-01],
        ...,
        [2.3305e-01, 1.6420e-01, 9.7741e-01,  ..., 8.0215e-01, 6.8775e-01,
         9.5870e-01],
        [4.3756e-01, 6.2796e-01, 3.7611e-01,  ..., 4.4400e-01, 5.9617e-01,
         7.1104e-02],
        [2.7188e-01, 9.7977e-01, 1.0478e-02,  ..., 5.6490e-02, 1.0391e-02,
         6.5182e-02]])


tensor([[[5.3200e+02, 5.3200e+02, 5.3200e+02,  ..., 5.3200e+02,
          5.3200e+02, 5.3200e+02],
         [9.9275e-01, 2.1228e-01, 3.9331e-01,  ..., 5.6738e-01,
          6.7587e-01, 1.0177e-01],
         [6.1023e-01, 6.9942e-01, 5.8117e-01,  ..., 8.5050e-01,
          9.1666e-01, 2.3597e-01],
         ...,
         [2.3305e-01, 1.6420e-01, 9.7741e-01,  ..., 8.0215e-01,
          6.8775e-01, 9.5870e-01],
         [4.3756e-01, 6.2796e-01, 3.7611e-01,  ..., 4.4400e-01,
          5.9617e-01, 7.1104e-02],
         [2.7188e-01, 9.7977e-01, 1.0478e-02,  ..., 5.6490e-02,
          1.0391e-02, 6.5182e-02]],

        [[9.9382e-01, 5.1614e-01, 4.1426e-01,  ..., 1.9533e-01,
          9.0803e-01, 7.8899e-01],
         [4.1648e-01, 1.6428e-01, 4.5790e-01,  ..., 5.0348e-01,
          8.3161e-02, 7.7111e-02],
         [2.7951e-01, 9.2491e-01, 5.9730e-01,  ..., 2.4208e-01,
          8.9838e-01, 2.2860e-01],
         ...,
         [1.1207e-01, 6.6820e-01, 2.0400e-01,  ..., 3.9366e-01,
          3.891

----------
## Indexing (selecting data from tensors)
Similar with numpy

In [105]:
a = torch.arange(1,10).reshape(1,3,3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [106]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [110]:
a[0][0]

tensor([1, 2, 3])

In [112]:
# Last dimension
a[0][0][0]

tensor(1)

In [113]:
a[:,0]

tensor([[1, 2, 3]])

In [114]:
# Get all the values of 0th and 1stdimensions but ony ndex 1 of 2nd dimension
a[:,:,1]

tensor([[2, 5, 8]])

In [115]:
a[:,1,1]

tensor([5])

In [117]:
a[0,0,:]

tensor([1, 2, 3])

In [119]:
# Index on a to return 9
print(a[0, 2, 2])
print(a[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


---------
## PyTorch tensors & Numpy