In [1]:
import torch

In [2]:
data = [[1,2,3],
        [4,5,6]]
my_tensor = torch.tensor(data)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
my_tensor.shape

torch.Size([2, 3])

In [4]:
my_tensor.dtype

torch.int64

In [5]:
a = my_tensor
b = torch.tensor([[2,2,5],
                  [3,3,2]])

In [6]:
a+b

tensor([[3, 4, 8],
        [7, 8, 8]])

In [7]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

corrected_temperatures = adjustment + 2
print("Corrected temperatures:", corrected_temperatures)

Corrected temperatures: tensor([[4, 4, 4],
        [4, 4, 4]])


In [8]:
import torch.nn as nn

In [9]:
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]]
)
linear_layer = nn.Linear(in_features=3,out_features=2)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[ 0.8368, -0.3480]], grad_fn=<AddmmBackward0>)

![description](scher.png)

In [11]:
linear_layer.weight

Parameter containing:
tensor([[ 0.4753,  0.4127, -0.1825],
        [-0.4593,  0.0502,  0.0853]], requires_grad=True)

In [12]:
linear_layer.bias

Parameter containing:
tensor([ 0.4412, -0.1913], requires_grad=True)

![description](scher2.png)

In [13]:
model = nn.Sequential(
    nn.Linear(n_features, 8), # n_features represents number of input features
    nn.Linear(8,4),
    nn.Linear(4, n_classes) # n_classes represents number of output classes
)

NameError: name 'n_features' is not defined

In [14]:
model = nn.Sequential(
    nn.Linear(5, 8),
    nn.Linear(8,4),
    nn.Linear(4, 10)
)

In [15]:
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,2)
)
total = 0
for parameter in model.parameters():
    total += parameter.numel()
total

46

![description](scher3.png)

In [16]:
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
output

tensor([[0.9975]])

In [17]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/Users/mclight/Downloads/GitHub/AI_Self-Study/.conda/lib/python3.11/site-packages/torch/nn/modules/module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [18]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# 4-layer linear network
model = nn.Sequential(
    nn.Linear(11, 16),
    nn.Linear(16, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 1),
)

output = model(input_tensor)
print(output)

tensor([[1.0973]], grad_fn=<AddmmBackward0>)


In [20]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Multi-class classification model
model = nn.Sequential(
    nn.Linear(11, 16),
    nn.Linear(16, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 3),
    nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.4122, 0.0789, 0.5088]], grad_fn=<SoftmaxBackward0>)


/Users/mclight/Downloads/GitHub/AI_Self-Study/.conda/lib/python3.11/site-packages/torch/nn/modules/module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [21]:
import torch.nn.functional as F
print(F.one_hot(torch.tensor(0), num_classes=3))

tensor([1, 0, 0])


In [ ]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([-5.2, 4.6, 0.8])
one_hot_target = torch.tensor([1,0,0])

criterion = CrossEntropyLoss()
print(criterion(scores.double(),one_hot_target.double()))

tensor(9.8222, dtype=torch.float64)


![description](scher4.png)

![descrpition](scher5.png)

![description](scher6.png)

In [ ]:
model = nn.Sequential(
    nn.Linear(16,8),
    nn.Linear(8,4),
    nn.Linear(4,2)
)

prediction = model(sample)

# Calcuate the loss. and gradiens

criterion = CrossEntropyLoss()
loss = criterion(prediction, target)
loss.backward()


# * * * * 
model[0].wieght.grad
model[0].bias.grad
model[1].wieght.grad
model[1].bias.grad
model[2].wieght.grad
model[2].bias.grad

# Learning rate is typically small
lr = 0.001

# update weights
weight = model[0].weight
weight_grad = model[0].weight.grad

weight = weight - lr * weight_grad

# Update the biases
bias = model[0].bias
bias_grad = model[0].bias.grad

bias = bias - lr * bias_grad

![description](scher7.png)

In [25]:
import torch.optim as optim

# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr = 0.001)

# Perform parameter updates
optimizer.step()

---------
## Introduction to Deep Learning with PyTorch

In [ ]:
import torch
from torch.utils.data import TensorDataset

# Instantiate dataset class
dataset = TensorDataset(torch.tensor(X), torch.tensor(y))

# Access ab individual sample
input_sample, label_sample = dateset[0]
input_sample, label_sample

In [ ]:
from torch.utils.data import DataLoader

batch_size=2
shuffle = True

# create a DataLoader
dataloader = DataLoader(dataset, batch_size = batch_size, shuffle=shuffle)

In [26]:
for batch_inputs, batch_labels in dataloader:
    print(batch_inputs, batch_labels)

NameError: name 'dataloader' is not defined

---------
## Training neural network

1. Create a model
2. Choose a loss function
3. Define a dataset
4. Set an optimizer
5. Run a training loop:
    - Calculate loss (forward pass)
    - Compute graadients (backpropagation)
    - Updating model parameters

In [28]:
# in PyTorch
criterion = nn.MSELoss()
loss = criterion(prediction, target)

NameError: name 'prediction' is not defined

In [29]:
dataset = TensorDataset(
    torch.tensor(features).float(),
    torch.tensor(target).float()
)

NameError: name 'TensorDataset' is not defined